apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: callme
  name: callme
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: callme
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: callme
    spec:
      containers:
      - image: gcr.io/k8s-springboot/callme:v1 #CHANGE
        imagePullPolicy: IfNotPresent
        name: callme
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: callme
  name: callme
  namespace: default
spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8002 #CHANGE
    protocol: TCP
    targetPort: 8002 #CHANGE
  selector:
    app: callme
  sessionAffinity: None #CHANGE
  type: LoadBalancer