apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: caller
  name: caller
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: caller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: caller
    spec:
      containers:
      - image: gcr.io/k8s-springboot/caller:v1 #CHANGE
        imagePullPolicy: IfNotPresent
        name: caller
        env:
          - name: CALLME_SERVICE_URI
            value: http://callme
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: caller
  name: caller
  namespace: default
spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8001 #CHANGE
    protocol: TCP
    targetPort: 8001 #CHANGE
  selector:
    app: caller
  sessionAffinity: None #CHANGE
  type: LoadBalancer